//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEtudiant.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class details
    {
        public string modules { get; set; }
        public string annee { get; set; }
        public int classe_id { get; set; }
        public int professeur_id { get; set; }
    
        public virtual classe classe { get; set; }
        public virtual personne personne { get; set; }
    }
}
